Jsonintegration
mdelez/ElmWind pull request #3
Opened 2022-02-04 17:29 UTC by EricSommerhalder

2022-02-04 17:30 UTC, EricSommerhalder commented
f the conflicts

2022-02-07 11:42 UTC, mdelez requested changes

2022-02-07 11:42 UTC, mdelez commented on index.html
> +try {
why is the whole `app.js` here? 😅

2022-02-07 11:42 UTC, mdelez commented on src/Dropdown.elm
> +                {-[ a
is this commented code needed?

2022-02-07 11:42 UTC, mdelez commented on test_data.json
> +    "header" : "Best MTG color",
might be better to use the word "label" here

2022-02-07 11:42 UTC, mdelez commented on with_json.html
> +                console.log(data[i])
please remove the console.log :)

2022-02-17 16:05 UTC, closed without merging